// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZVamGULEVlQyaa0b-hcvFqrvrbkUv0Q',
    appId: '1:1085944093717:web:ca6cafb339bb0a5e2d421c',
    messagingSenderId: '1085944093717',
    projectId: 'rms-app-3d585',
    authDomain: 'rms-app-3d585.firebaseapp.com',
    storageBucket: 'rms-app-3d585.firebasestorage.app',
    measurementId: 'G-88SK4X45J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC155e-ThyIV1-O5ePyfKGsrrEibW817SI',
    appId: '1:1085944093717:android:85eef057da5a129a2d421c',
    messagingSenderId: '1085944093717',
    projectId: 'rms-app-3d585',
    storageBucket: 'rms-app-3d585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6pQ5xLk2ainN0AN61Om-tqun_OlWeni8',
    appId: '1:1085944093717:ios:43370b71e0f785532d421c',
    messagingSenderId: '1085944093717',
    projectId: 'rms-app-3d585',
    storageBucket: 'rms-app-3d585.firebasestorage.app',
    iosBundleId: 'com.example.rmsApp',
  );
}
